// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: registry-monitor.proto

package registry_monitor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistryMonitorService_CheckUpdates_FullMethodName = "/registrymonitor.RegistryMonitorService/CheckUpdates"
)

// RegistryMonitorServiceClient is the client API for RegistryMonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==========================
// Service
// ==========================
type RegistryMonitorServiceClient interface {
	// Orchestrator calls this to check for updates on a batch of images
	CheckUpdates(ctx context.Context, in *CheckUpdatesRequest, opts ...grpc.CallOption) (*CheckUpdatesResponse, error)
}

type registryMonitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryMonitorServiceClient(cc grpc.ClientConnInterface) RegistryMonitorServiceClient {
	return &registryMonitorServiceClient{cc}
}

func (c *registryMonitorServiceClient) CheckUpdates(ctx context.Context, in *CheckUpdatesRequest, opts ...grpc.CallOption) (*CheckUpdatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUpdatesResponse)
	err := c.cc.Invoke(ctx, RegistryMonitorService_CheckUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryMonitorServiceServer is the server API for RegistryMonitorService service.
// All implementations must embed UnimplementedRegistryMonitorServiceServer
// for forward compatibility.
//
// ==========================
// Service
// ==========================
type RegistryMonitorServiceServer interface {
	// Orchestrator calls this to check for updates on a batch of images
	CheckUpdates(context.Context, *CheckUpdatesRequest) (*CheckUpdatesResponse, error)
	mustEmbedUnimplementedRegistryMonitorServiceServer()
}

// UnimplementedRegistryMonitorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryMonitorServiceServer struct{}

func (UnimplementedRegistryMonitorServiceServer) CheckUpdates(context.Context, *CheckUpdatesRequest) (*CheckUpdatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUpdates not implemented")
}
func (UnimplementedRegistryMonitorServiceServer) mustEmbedUnimplementedRegistryMonitorServiceServer() {
}
func (UnimplementedRegistryMonitorServiceServer) testEmbeddedByValue() {}

// UnsafeRegistryMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryMonitorServiceServer will
// result in compilation errors.
type UnsafeRegistryMonitorServiceServer interface {
	mustEmbedUnimplementedRegistryMonitorServiceServer()
}

func RegisterRegistryMonitorServiceServer(s grpc.ServiceRegistrar, srv RegistryMonitorServiceServer) {
	// If the following call pancis, it indicates UnimplementedRegistryMonitorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistryMonitorService_ServiceDesc, srv)
}

func _RegistryMonitorService_CheckUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryMonitorServiceServer).CheckUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryMonitorService_CheckUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryMonitorServiceServer).CheckUpdates(ctx, req.(*CheckUpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryMonitorService_ServiceDesc is the grpc.ServiceDesc for RegistryMonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryMonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registrymonitor.RegistryMonitorService",
	HandlerType: (*RegistryMonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUpdates",
			Handler:    _RegistryMonitorService_CheckUpdates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry-monitor.proto",
}
