# Example configuration file for local development.
env: # "dev"
DataBaseURL: # "http://postgres:5432"
gRPCServer:
  Address: # ""0.0.0.0:50051"
  # Address for the gRPC server, e.g., ""0.0.0.0:50051"
