// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: containers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStaleContainersForHost = `-- name: DeleteStaleContainersForHost :exec
DELETE FROM containers
WHERE host_id = $1 AND container_uid <> ALL($2::text[])
`

type DeleteStaleContainersForHostParams struct {
	HostID  pgtype.UUID `json:"host_id"`
	Column2 []string    `json:"column_2"`
}

// Deletes containers for a given host that are not in the provided list of UIDs.
func (q *Queries) DeleteStaleContainersForHost(ctx context.Context, arg DeleteStaleContainersForHostParams) error {
	_, err := q.db.Exec(ctx, deleteStaleContainersForHost, arg.HostID, arg.Column2)
	return err
}

const getContainerbyContainerUID = `-- name: GetContainerbyContainerUID :one
SELECT id, container_uid, host_id, name, image, digest, ports, env_vars, volumes, network, watch, created_at FROM containers WHERE container_uid = $1
`

// Retrieves a container by its UID
func (q *Queries) GetContainerbyContainerUID(ctx context.Context, containerUid string) (Container, error) {
	row := q.db.QueryRow(ctx, getContainerbyContainerUID, containerUid)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.ContainerUid,
		&i.HostID,
		&i.Name,
		&i.Image,
		&i.Digest,
		&i.Ports,
		&i.EnvVars,
		&i.Volumes,
		&i.Network,
		&i.Watch,
		&i.CreatedAt,
	)
	return i, err
}

const getHostbyContainerUID = `-- name: GetHostbyContainerUID :one
SELECT h.id, h.mac_address, h.hostname, h.ip_address, h.last_heartbeat, h.created_at
FROM hosts h
JOIN containers c ON h.id = c.host_id
WHERE c.container_uid = $1
`

// Retrieves the host associated with a given container UID
func (q *Queries) GetHostbyContainerUID(ctx context.Context, containerUid string) (Host, error) {
	row := q.db.QueryRow(ctx, getHostbyContainerUID, containerUid)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.Hostname,
		&i.IpAddress,
		&i.LastHeartbeat,
		&i.CreatedAt,
	)
	return i, err
}

const getallContainersWhereWatched = `-- name: GetallContainersWhereWatched :many
SELECT id, container_uid, host_id, name, image, digest, ports, env_vars, volumes, network, watch, created_at FROM containers WHERE watch = TRUE
`

// Retrieves all containers where watched is true
func (q *Queries) GetallContainersWhereWatched(ctx context.Context) ([]Container, error) {
	rows, err := q.db.Query(ctx, getallContainersWhereWatched)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Container
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ID,
			&i.ContainerUid,
			&i.HostID,
			&i.Name,
			&i.Image,
			&i.Digest,
			&i.Ports,
			&i.EnvVars,
			&i.Volumes,
			&i.Network,
			&i.Watch,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertContainer = `-- name: InsertContainer :one
INSERT INTO containers (
  container_uid,
  host_id,
  name,
  image,
  digest,
  ports,
  env_vars,
  volumes,
  network
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (container_uid)
DO UPDATE SET
  host_id = EXCLUDED.host_id,
  name = EXCLUDED.name,
  image = EXCLUDED.image,
  digest = EXCLUDED.digest,
  ports = EXCLUDED.ports,
  env_vars = EXCLUDED.env_vars,
  volumes = EXCLUDED.volumes,
  network = EXCLUDED.network
RETURNING id, container_uid, host_id, name, image, digest, ports, env_vars, volumes, network, watch, created_at
`

type InsertContainerParams struct {
	ContainerUid string      `json:"container_uid"`
	HostID       pgtype.UUID `json:"host_id"`
	Name         string      `json:"name"`
	Image        string      `json:"image"`
	Digest       string      `json:"digest"`
	Ports        []string    `json:"ports"`
	EnvVars      []string    `json:"env_vars"`
	Volumes      []string    `json:"volumes"`
	Network      pgtype.Text `json:"network"`
}

// Inserts or updates container based on container_uid
func (q *Queries) InsertContainer(ctx context.Context, arg InsertContainerParams) (Container, error) {
	row := q.db.QueryRow(ctx, insertContainer,
		arg.ContainerUid,
		arg.HostID,
		arg.Name,
		arg.Image,
		arg.Digest,
		arg.Ports,
		arg.EnvVars,
		arg.Volumes,
		arg.Network,
	)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.ContainerUid,
		&i.HostID,
		&i.Name,
		&i.Image,
		&i.Digest,
		&i.Ports,
		&i.EnvVars,
		&i.Volumes,
		&i.Network,
		&i.Watch,
		&i.CreatedAt,
	)
	return i, err
}
