// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hosts.sql

package db

import (
	"context"
)

const insertHost = `-- name: InsertHost :one
INSERT INTO hosts (
  mac_address,
  hostname,
  ip_address
) VALUES (
  $1, $2, $3
)
ON CONFLICT (mac_address)
DO UPDATE SET
  hostname = EXCLUDED.hostname,
  ip_address = EXCLUDED.ip_address
RETURNING id, mac_address, hostname, ip_address, last_heartbeat, created_at
`

type InsertHostParams struct {
	MacAddress string `json:"mac_address"`
	Hostname   string `json:"hostname"`
	IpAddress  string `json:"ip_address"`
}

// Inserts a new host or updates an existing one based on the MAC address.
func (q *Queries) InsertHost(ctx context.Context, arg InsertHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, insertHost, arg.MacAddress, arg.Hostname, arg.IpAddress)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.Hostname,
		&i.IpAddress,
		&i.LastHeartbeat,
		&i.CreatedAt,
	)
	return i, err
}
