// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	// Inserts or updates container based on container_uid
	InsertContainer(ctx context.Context, arg InsertContainerParams) (Container, error)
	// Inserts a new host or updates an existing one based on the MAC address.
	InsertHost(ctx context.Context, arg InsertHostParams) (Host, error)
}

var _ Querier = (*Queries)(nil)
