// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_status.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUpdateStatus = `-- name: InsertUpdateStatus :one
INSERT INTO update_status (
  host_id,
  stage,
  logs,
  image
  ) 
VALUES (
  $1, $2, $3, $4
) RETURNING id, image, host_id, stage, logs, created_at
`

type InsertUpdateStatusParams struct {
	HostID pgtype.UUID `json:"host_id"`
	Stage  UpdateStage `json:"stage"`
	Logs   pgtype.Text `json:"logs"`
	Image  string      `json:"image"`
}

// Updates the status of a deployment.
func (q *Queries) InsertUpdateStatus(ctx context.Context, arg InsertUpdateStatusParams) (UpdateStatus, error) {
	row := q.db.QueryRow(ctx, insertUpdateStatus,
		arg.HostID,
		arg.Stage,
		arg.Logs,
		arg.Image,
	)
	var i UpdateStatus
	err := row.Scan(
		&i.ID,
		&i.Image,
		&i.HostID,
		&i.Stage,
		&i.Logs,
		&i.CreatedAt,
	)
	return i, err
}
