// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: host-agent.proto

package host_agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateStatus_Stage int32

const (
	UpdateStatus_UNKNOWN      UpdateStatus_Stage = 0
	UpdateStatus_PULLING      UpdateStatus_Stage = 1
	UpdateStatus_STARTING     UpdateStatus_Stage = 2
	UpdateStatus_HEALTH_CHECK UpdateStatus_Stage = 3
	UpdateStatus_COMPLETED    UpdateStatus_Stage = 4
	UpdateStatus_ROLLBACK     UpdateStatus_Stage = 5
	UpdateStatus_FAILED       UpdateStatus_Stage = 6
)

// Enum value maps for UpdateStatus_Stage.
var (
	UpdateStatus_Stage_name = map[int32]string{
		0: "UNKNOWN",
		1: "PULLING",
		2: "STARTING",
		3: "HEALTH_CHECK",
		4: "COMPLETED",
		5: "ROLLBACK",
		6: "FAILED",
	}
	UpdateStatus_Stage_value = map[string]int32{
		"UNKNOWN":      0,
		"PULLING":      1,
		"STARTING":     2,
		"HEALTH_CHECK": 3,
		"COMPLETED":    4,
		"ROLLBACK":     5,
		"FAILED":       6,
	}
)

func (x UpdateStatus_Stage) Enum() *UpdateStatus_Stage {
	p := new(UpdateStatus_Stage)
	*p = x
	return p
}

func (x UpdateStatus_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateStatus_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_host_agent_proto_enumTypes[0].Descriptor()
}

func (UpdateStatus_Stage) Type() protoreflect.EnumType {
	return &file_host_agent_proto_enumTypes[0]
}

func (x UpdateStatus_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateStatus_Stage.Descriptor instead.
func (UpdateStatus_Stage) EnumDescriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{4, 0}
}

type ContainerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerID   string                 `protobuf:"bytes,1,opt,name=containerID,proto3" json:"containerID,omitempty"` // Docker container ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // Container name
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`             // Image name with tag
	Ports         []string               `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`             // Exposed ports
	EnvVars       []string               `protobuf:"bytes,6,rep,name=envVars,proto3" json:"envVars,omitempty"`         // Environment variables
	Volumes       []string               `protobuf:"bytes,7,rep,name=volumes,proto3" json:"volumes,omitempty"`         // Mounted volumes
	Network       string                 `protobuf:"bytes,8,opt,name=network,proto3" json:"network,omitempty"`         // Network name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_host_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerInfo) GetContainerID() string {
	if x != nil {
		return x.ContainerID
	}
	return ""
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerInfo) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerInfo) GetEnvVars() []string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *ContainerInfo) GetVolumes() []string {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *ContainerInfo) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type HostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostID        string                 `protobuf:"bytes,1,opt,name=hostID,proto3" json:"hostID,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Containers    []*ContainerInfo       `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_host_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{1}
}

func (x *HostInfo) GetHostID() string {
	if x != nil {
		return x.HostID
	}
	return ""
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HostInfo) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostID        string                 `protobuf:"bytes,1,opt,name=hostID,proto3" json:"hostID,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_host_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetHostID() string {
	if x != nil {
		return x.HostID
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UpdateContainerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeploymentID    string                 `protobuf:"bytes,1,opt,name=deploymentID,proto3" json:"deploymentID,omitempty"`       // Internal orchestrator deployment ID
	Image           string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`                     // New image (repo:tag or digest)
	OverrideEnvVars []string               `protobuf:"bytes,3,rep,name=overrideEnvVars,proto3" json:"overrideEnvVars,omitempty"` // Optional overrides
	OverridePorts   []string               `protobuf:"bytes,4,rep,name=overridePorts,proto3" json:"overridePorts,omitempty"`     // Optional overrides
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateContainerRequest) Reset() {
	*x = UpdateContainerRequest{}
	mi := &file_host_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContainerRequest) ProtoMessage() {}

func (x *UpdateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContainerRequest.ProtoReflect.Descriptor instead.
func (*UpdateContainerRequest) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateContainerRequest) GetDeploymentID() string {
	if x != nil {
		return x.DeploymentID
	}
	return ""
}

func (x *UpdateContainerRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *UpdateContainerRequest) GetOverrideEnvVars() []string {
	if x != nil {
		return x.OverrideEnvVars
	}
	return nil
}

func (x *UpdateContainerRequest) GetOverridePorts() []string {
	if x != nil {
		return x.OverridePorts
	}
	return nil
}

type UpdateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentID  string                 `protobuf:"bytes,1,opt,name=deploymentID,proto3" json:"deploymentID,omitempty"`
	ContainerID   string                 `protobuf:"bytes,2,opt,name=containerID,proto3" json:"containerID,omitempty"`
	Stage         UpdateStatus_Stage     `protobuf:"varint,3,opt,name=stage,proto3,enum=hostagent.UpdateStatus_Stage" json:"stage,omitempty"`
	Logs          string                 `protobuf:"bytes,4,opt,name=logs,proto3" json:"logs,omitempty"` // Optional log snippet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatus) Reset() {
	*x = UpdateStatus{}
	mi := &file_host_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatus) ProtoMessage() {}

func (x *UpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatus.ProtoReflect.Descriptor instead.
func (*UpdateStatus) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStatus) GetDeploymentID() string {
	if x != nil {
		return x.DeploymentID
	}
	return ""
}

func (x *UpdateStatus) GetContainerID() string {
	if x != nil {
		return x.ContainerID
	}
	return ""
}

func (x *UpdateStatus) GetStage() UpdateStatus_Stage {
	if x != nil {
		return x.Stage
	}
	return UpdateStatus_UNKNOWN
}

func (x *UpdateStatus) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

var File_host_agent_proto protoreflect.FileDescriptor

const file_host_agent_proto_rawDesc = "" +
	"\n" +
	"\x10host-agent.proto\x12\thostagent\"\xbf\x01\n" +
	"\rContainerInfo\x12 \n" +
	"\vcontainerID\x18\x01 \x01(\tR\vcontainerID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05ports\x18\x05 \x03(\tR\x05ports\x12\x18\n" +
	"\aenvVars\x18\x06 \x03(\tR\aenvVars\x12\x18\n" +
	"\avolumes\x18\a \x03(\tR\avolumes\x12\x18\n" +
	"\anetwork\x18\b \x01(\tR\anetwork\"\x88\x01\n" +
	"\bHostInfo\x12\x16\n" +
	"\x06hostID\x18\x01 \x01(\tR\x06hostID\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x128\n" +
	"\n" +
	"containers\x18\x04 \x03(\v2\x18.hostagent.ContainerInfoR\n" +
	"containers\"H\n" +
	"\x10HeartbeatRequest\x12\x16\n" +
	"\x06hostID\x18\x01 \x01(\tR\x06hostID\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xa2\x01\n" +
	"\x16UpdateContainerRequest\x12\"\n" +
	"\fdeploymentID\x18\x01 \x01(\tR\fdeploymentID\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12(\n" +
	"\x0foverrideEnvVars\x18\x03 \x03(\tR\x0foverrideEnvVars\x12$\n" +
	"\roverridePorts\x18\x04 \x03(\tR\roverridePorts\"\x89\x02\n" +
	"\fUpdateStatus\x12\"\n" +
	"\fdeploymentID\x18\x01 \x01(\tR\fdeploymentID\x12 \n" +
	"\vcontainerID\x18\x02 \x01(\tR\vcontainerID\x123\n" +
	"\x05stage\x18\x03 \x01(\x0e2\x1d.hostagent.UpdateStatus.StageR\x05stage\x12\x12\n" +
	"\x04logs\x18\x04 \x01(\tR\x04logs\"j\n" +
	"\x05Stage\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPULLING\x10\x01\x12\f\n" +
	"\bSTARTING\x10\x02\x12\x10\n" +
	"\fHEALTH_CHECK\x10\x03\x12\r\n" +
	"\tCOMPLETED\x10\x04\x12\f\n" +
	"\bROLLBACK\x10\x05\x12\n" +
	"\n" +
	"\x06FAILED\x10\x062\xae\x02\n" +
	"\x10HostAgentService\x128\n" +
	"\fRegisterHost\x12\x13.hostagent.HostInfo\x1a\x13.hostagent.HostInfo\x12E\n" +
	"\tHeartbeat\x12\x1b.hostagent.HeartbeatRequest\x1a\x1b.hostagent.HeartbeatRequest\x12M\n" +
	"\x0fUpdateContainer\x12!.hostagent.UpdateContainerRequest\x1a\x17.hostagent.UpdateStatus\x12J\n" +
	"\x12UpdateStatusStream\x12\x17.hostagent.UpdateStatus\x1a\x17.hostagent.UpdateStatus(\x010\x01B@Z>github.com/MadhavKrishanGoswami/Lighthouse/services/host-agentb\x06proto3"

var (
	file_host_agent_proto_rawDescOnce sync.Once
	file_host_agent_proto_rawDescData []byte
)

func file_host_agent_proto_rawDescGZIP() []byte {
	file_host_agent_proto_rawDescOnce.Do(func() {
		file_host_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_host_agent_proto_rawDesc), len(file_host_agent_proto_rawDesc)))
	})
	return file_host_agent_proto_rawDescData
}

var file_host_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_host_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_host_agent_proto_goTypes = []any{
	(UpdateStatus_Stage)(0),        // 0: hostagent.UpdateStatus.Stage
	(*ContainerInfo)(nil),          // 1: hostagent.ContainerInfo
	(*HostInfo)(nil),               // 2: hostagent.HostInfo
	(*HeartbeatRequest)(nil),       // 3: hostagent.HeartbeatRequest
	(*UpdateContainerRequest)(nil), // 4: hostagent.UpdateContainerRequest
	(*UpdateStatus)(nil),           // 5: hostagent.UpdateStatus
}
var file_host_agent_proto_depIdxs = []int32{
	1, // 0: hostagent.HostInfo.containers:type_name -> hostagent.ContainerInfo
	0, // 1: hostagent.UpdateStatus.stage:type_name -> hostagent.UpdateStatus.Stage
	2, // 2: hostagent.HostAgentService.RegisterHost:input_type -> hostagent.HostInfo
	3, // 3: hostagent.HostAgentService.Heartbeat:input_type -> hostagent.HeartbeatRequest
	4, // 4: hostagent.HostAgentService.UpdateContainer:input_type -> hostagent.UpdateContainerRequest
	5, // 5: hostagent.HostAgentService.UpdateStatusStream:input_type -> hostagent.UpdateStatus
	2, // 6: hostagent.HostAgentService.RegisterHost:output_type -> hostagent.HostInfo
	3, // 7: hostagent.HostAgentService.Heartbeat:output_type -> hostagent.HeartbeatRequest
	5, // 8: hostagent.HostAgentService.UpdateContainer:output_type -> hostagent.UpdateStatus
	5, // 9: hostagent.HostAgentService.UpdateStatusStream:output_type -> hostagent.UpdateStatus
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_host_agent_proto_init() }
func file_host_agent_proto_init() {
	if File_host_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_host_agent_proto_rawDesc), len(file_host_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_host_agent_proto_goTypes,
		DependencyIndexes: file_host_agent_proto_depIdxs,
		EnumInfos:         file_host_agent_proto_enumTypes,
		MessageInfos:      file_host_agent_proto_msgTypes,
	}.Build()
	File_host_agent_proto = out.File
	file_host_agent_proto_goTypes = nil
	file_host_agent_proto_depIdxs = nil
}
